README.md
deploy/04_must-gather-admin.ServiceAccount.yaml
deploy/05_must-gather-admin.ClusterRoleBinding.yaml
hack/olm-registry/olm-artifacts-template.yaml
hack/templates/csv.yaml

Clean up references to SA and CRB in README
Additionally, ensure all namespace references indicate openshift-must-gather-operator
Updated generated olm-artifacts-template (ran make)

Add must-gather-admin ServiceAccount and ClusterRoleBinding OSD-5236

---

cmd/manager/main.go
deploy/02_cluster_role.yaml
deploy/04_prometheus-k8s_role.yaml
deploy/05_prometheus-k8s_role_binding.yaml
go.mod
go.sum
pkg/controller/mustgather/mustgather_controller.go
pkg/localmetrics/localmetrics.go

This adds prometheus custom metrics in order to have some observability of the operator via on-cluster prometheus.
Example of new metrics added:
```
must_gather_operator_must_gather_errors 1
must_gather_operator_must_gather_total 2
```

Add Prometheus Custom Metrics

---

build/bin/upload
hack/olm-registry/olm-artifacts-template.yaml
hack/templates/selectorsyncset.yaml

Because new tokens may only be used one time, and only provide the user with upload permissions, we can no longer check the login credentials before uploading the m-g file, nor can we attempt to mkdir or cd into that dir
Uploading the file immediately upon login (without worrying about directory structures) works to get the file uploaded successfully to the case - see https://access.redhat.com/support/cases/#/case/02715548

Revert operator disablement and modify MGO to play nice with new one-time upload-only tokens

---

build/Dockerfile
build/bin/upload
build/templates/job.template.yaml
deploy/crds/managed.openshift.io_mustgathers.yaml
examples/mustgather_non_internal_user.yaml
examples/mustgather_timeout.yaml
go.mod
go.sum
pkg/apis/mustgather/v1alpha1/mustgather_types.go
pkg/apis/mustgather/v1alpha1/zz_generated.openapi.go
pkg/controller/mustgather/mustgather_controller.go

This PR proposes a couple of changes.
- The `/usr/local/bin/gather` are executed as full containers, and not initcontainers. This has two major advantages. 
1. Gather from multiple images can run in parallel instead of sequentially 
2. `oc logs` on the `gather` container(s) will now return some logs
- In this parallel gathering approach, the `upload` container needs to be aware of the end of all gathers. This is why all containers are sharing the same process namespace and the `upload` container monitors `gather` processes for termination. 
- The introduction of a timeout for the gathers. This is made available through the MustGather CR in `spec.mustGatherTimeout`. It should protect against hanging `gather` containers. By default, it is not activated. 
- The introduction of a new flag …

OSD-8230 - adding a timeout to /usr/bin/gather

---

pkg/controller/mustgather/mustgather_controller.go

reassign the value of tmpPod in for loop to prevent  G601: Implicit memory aliasing in for loop when running golangci gosec lint:
`test "/home/linnguye/golangci.yml" = "" || test ! -e "/home/linnguye/golangci.yml" || GOLANGCI_LINT_CACHE="/tmp/golangci-cache" golangci-lint run -c "/home/linnguye/golangci.yml" ./...
pkg/controller/mustgather/mustgather_controller.go:260:50: G601: Implicit memory aliasing in for loop. (gosec)
err = r.GetClient().Delete(context.TODO(), &tmpPod)
^
make: *** [boilerplate/openshift/golang-osd-operator/standard.mk:171: go-check] Error 1
`
Jira card: https://issues.redhat.com/browse/OSD-11458

reassign the value of tmpPod

---

pkg/controller/mustgather/mustgather_controller_test.go

Justification: code is tied to a specific controller-runtime version, security has agree to let this test be hidden. Here's the output when running golangci goesc lint
`pkg/controller/mustgather/mustgather_controller_test.go:16:2: SA1019: package sigs.k8s.io/controller-runtime/pkg/client/fake is deprecated: please use pkg/envtest for testing. This package will be dropped before the v1.0.0 release. Package fake provides a fake client for testing. (staticcheck)
"sigs.k8s.io/controller-runtime/pkg/client/fake"
`
Jira card: https://issues.redhat.com/browse/OSD-11458

added //nolint:staticcheck to hide package depreciated check

---

api/v1alpha1/mustgather_types.go
api/v1alpha1/zz_generated.openapi.go
build/templates/job.template.yaml
deploy/crds/managed.openshift.io_mustgathers.yaml

Added a new field **audit** in the must-gather CRD, that when set to **true**, it uses the `gather_audit_logs` binary which exists already in the must-gather image.
```apiVersion: managed.openshift.io/v1alpha1
kind: MustGather
metadata:
name: example-mustgather-full
spec:
caseID: '02527285'
caseManagementAccountSecretRef:
name: case-management-creds
serviceAccountRef:
name: must-gather-admin
audit: true 
```

Added logic in job.template to gather audit logs

---

hack/olm-registry/olm-artifacts-template.yaml

the CatalogSource spec does not define `affinity` or `tolerations` at
the `spec` level. That is already set in the `grpcPodConfig`
https://issues.redhat.com/browse/SDCICD-1178
https://docs.openshift.com/container-platform/4.14/rest_api/operatorhub_apis/catalogsource-operators-coreos-com-v1alpha1.html
/cleanup
Signed-off-by: Brady Pratt <bpratt@redhat.com>

SDCICD-1178: remove unknown fields from schema

---

hack/olm-registry/olm-artifacts-template.yaml

as a part of the on-going release versioning effort, adjust the behavior of the SelectorSyncSet to allow PKO to adopt the resources on a cluster and not be overwritten by Hive syncing.
Once Hive applies the resources, it will no longer try to resync the changes continuously which will allow Package Operator to take ownership of the resources and manage their lifecycle.
https://issues.redhat.com/browse/SDCICD-1286
https://docs.google.com/document/d/1cdJuVFk5OhSR6ceLKyBgSZjfPmsnWFeqab_EJUbI0t4/edit#heading=h.bi1qeu8b4rop

SDCICD-1286: set resourceApplyMode to Upsert

---

hack/olm-registry/olm-artifacts-template.yaml

This reverts commit 061ec15939c8b39c3b0e9193abe7d3ad81c7fb77.
this change shouldn't have been promoted to prod as per https://redhat-internal.slack.com/archives/CFJD1NZFT/p1714371443733169
will revert this again after the changes have been promoted to prod

Revert "SDCICD-1286: set resourceApplyMode to Upsert"

---

hack/olm-registry/olm-artifacts-template.yaml

this namespace resource exists (and is planned on being removed) in MCC and differs from this resource slightly. Sync the annotations and labels from that resource.
https://issues.redhat.com/browse/SDCICD-1292
https://github.com/openshift/managed-cluster-config/blob/adfaa3e71a3cc20e2ab444f0359e188ee6fb467c/deploy/osd-must-gather-operator/01-openshift-must-gather-operator.Namespace.yaml#L5-L9

hack/olm-registry: sync NS labels from MCC

---

README.md
api/v1alpha1/mustgather_types.go
api/v1alpha1/zz_generated.deepcopy.go
build/Dockerfile
build/Dockerfile.olm-registry
build/templates/job.template.yaml
controllers/mustgather/mustgather_controller.go
controllers/mustgather/mustgather_controller_test.go
deploy/02_must-gather-operator.ClusterRole.yaml
deploy/crds/managed.openshift.io_mustgathers.yaml
examples/mustgather_full.yaml
go.mod
go.sum
main.go

Follow up to OSD-21667 - we no longer need the ability to provide custom mustgather images.

remove ability to pass in custom mustgather images

---

controllers/mustgather/template.go
controllers/mustgather/template_test.go

Fixes a bug that was missed in https://github.com/openshift/must-gather-operator/pull/138 - we weren't using the secret key ref name to properly reference username/password envars in the upload container.
Relevant slack thread: https://redhat-internal.slack.com/archives/C016S65RNG5/p1718723911684519

Add secret key ref name to username and password env in upload container

---

controllers/mustgather/template.go
controllers/mustgather/template_test.go

These envars were missed during the refactor in https://github.com/openshift/must-gather-operator/pull/138 , and were recently discovered when checking for parity between the old job CRs created by MGO and the new job CRs.
Also some minor updates to the formatting of strings. In particular, the upload container's command went from this:
```
- command:
- /bin/bash
- -c
- "count=0\nuntil [ $count -gt 4 ]\ndo\n  while `pgrep -a gather > /dev/null`\n
\ do\n    echo \"waiting for gathers to complete ...\" \n    sleep 120\n
\   count=0\n  done\n  echo \"no gather is running ($count / 4)\"\n  ((count++))\n
\ sleep 30\ndone\n/usr/local/bin/upload\n"
```
To this:
```
- command:
- /bin/bash
- -c
- |-
count=0
until [ $count -gt 4 ]
do
while `pgrep -a gather > /dev/null`
do
echo "waiting for gathers …
```

Add missing envars to upload container

---

hack/olm-registry/olm-artifacts-template.yaml

Must Gather Operator is the first operator being switched from being deployed directly to hives using its own SelectorSyncSet to being deployed as part of the release bundle ([managed-release-bundle-osd.git](https://github.com/openshift/managed-release-bundle-osd), [SDE-3672](https://issues.redhat.com//browse/SDE-3672)).
First step is to switch the current SelectorSyncSet to `Upsert` mode, which will allow deleting the SelectorSyncSet entirely without Hives messing up any MGO deployments on clusters.

[SDCICD-1286] Set SSS mode to Upsert as prep for RVMO adoption

---

Makefile

Should fix Jenkins builds until https://issues.redhat.com/browse/SDCICD-1336 is done.

Workaround for insufficient release branch detection

---

deploy/99_must-gather-operator.Deployment.yaml
main.go
pkg/k8sutil/k8sutil.go

[OSD-21667](https://issues.redhat.com//browse/OSD-21667)
Hardening the security of operator resources by limiting the watch namespace to only reconcile when MustGathers are deployed in openshift-must-gather-operator.

Only watch operator namespace for MustGather CRs

---

config/config.go

With RVMO, the deployment pipeline is in control of the operator upgrades and we don't want OLM to try to be smart about it and try to think too much about which operator version can upgrade from which other version. We need it to just upgrade directly from whatever version is on the cluster to the newly-deployed version, no questions asked.
And that's what skiprange does. Instead of having all the previous versions listed explicitly in the OLM metadata, something like this is all that's going to in there:
```
"name": "stable",
"package": "osd-example-operator",
"entries": [
{
"name": "osd-example-operator.v4.16.193-633c3df",
"skipRange": ">=0.0.1 <4.16.193-633c3df"
}
]
```
which is equivalent to "you can upgrade to me directly from any version".

Generate OLM bundles that SkipRange everything

---

build/Dockerfile

Fixes https://issues.redhat.com/browse/OSD-24888 where MGO image builds are currently failing with error 
`error: Failed dependencies:
libc.so.6(GLIBC_2.15)(64bit) is needed by sshpass-1.06-9.el8.x86_64
libc.so.6(GLIBC_2.2.5)(64bit) is needed by sshpass-1.06-9.el8.x86_64
libc.so.6(GLIBC_2.3.4)(64bit) is needed by sshpass-1.06-9.el8.x86_64
libc.so.6(GLIBC_2.4)(64bit) is needed by sshpass-1.06-9.el8.x86_64
Error: building at STEP "RUN microdnf install tar gzip openssh-clients wget shadow-utils procps &&     wget https://kojipkgs.fedoraproject.org/packages/sshpass/1.06/9.el8/x86_64/sshpass-1.06-9.el8.x86_64.rpm &&     rpm -U sshpass-1.06-9.el8.x86_64.rpm &&     rm -f sshpass-1.06-9.el8.x86_64.rpm &&     microdnf clean all": while running runtime: exit status 1`

Fix operator build when setting up sshpass

---

OWNERS

With MGO being part of RVMO now, each change potentially means 6 PRs needing 6 lgtms.
This is going to be eventually solved with proper automation, but until it does, I'd prefer not to have bother people so much, while I make RVMO-related adjustments to MGO.

Add mmazur as an owner until branching PR automation is finished

---

hack/release-bundle/resources.yaml.gotmpl

In case there's a long Hive sync pause at the wrong moment for a cluster, it could be possible for the release bundle to not be able to then take over MGO objects. Let's make sure that's never possible by setting what is basically "let PKO take over the object ownership" setting permanently for all objects that were previously owned by Hive.
This setting has already been present temporarily during the "release bundle takeover of MGO" phase ([see](https://github.com/openshift/managed-release-bundle-osd/pull/156/files#diff-2be9963f7f06e8d851fb8897f94082e40daa415ee9bfdeb273b1b7f8c7c65870L5)), but then I dropped it. And in hindsight that was a mistake, so I'm reinstating it.

Make sure PKO can always take over Hive objects

---

osde2e/must_gather_operator_tests.go

now that this operator is migrated to RVMO, the old code that inspected the OLM bundle to find previous versions and upgrade from it no longer works. Disable the perm failing test

osde2e: mark upgrade test as pending

---

build/Dockerfile
build/Dockerfile.olm-registry
deploy/99_must-gather-operator.Deployment.yaml

Enforce CPU and MEM limits for the must gather Operator.
In order to choose the values I went into a long standing clusters to check over time how much MEM and CPU has been consuming. In addition I trigger a full must-must gather on the cluster in order to see possible spikes and consumption during the must gather. The operator itself consumes very low resources, since its only job is to read the presence of CR and deploy a Job on the cluster which will perform the gathering. The consumption of resources by this deployed must-gather pod and subsequent enforcement of limits will be done in another PR.

OSD-28575 added limits for MEM and CPU for must-gather-operator

---

bundle/bundle.Dockerfile
bundle/manifests/art.yaml
bundle/manifests/must-gather-operator.package.yaml
bundle/manifests/tech-preview/image-references
bundle/manifests/tech-preview/managed.openshift.io_mustgathers.yaml
bundle/manifests/tech-preview/must-gather-operator.clusterserviceversion.yaml
bundle/metadata/annotations.yaml

Follow-up over https://github.com/openshift-eng/ocp-build-data/pull/7302
Update and add `bundle/` directory to make ClusterServiceVersion and bundle build ART-istic (ready to be built and delivered by OpenShift Automated Release Tooling).
TODO(in follow-up)

MG-46: Make ART-istic bundle
